development:
  adapter: postgresql
  encoding: utf8
  database: mesprit_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: mesprit_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mesprit_production
  pool: 5
  username:
  password: